# Generated by Django 4.1.2 on 2022-10-12 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Psychologist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now=True, verbose_name="Data de criação"),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, verbose_name="Data de atualização"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "crp_register",
                    models.CharField(max_length=20, verbose_name="Registro CRP"),
                ),
                (
                    "professional_address",
                    models.CharField(
                        max_length=200, verbose_name="Endereço Profissional"
                    ),
                ),
                (
                    "secondary_address",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Endereço secundário",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=15, verbose_name="Telefone"),
                ),
                (
                    "cpf",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="CPF"
                    ),
                ),
                (
                    "psychologist",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Psicólogo(a)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Psicólogo",
                "verbose_name_plural": "Psicólogos",
            },
        ),
    ]
