# Generated by Django 4.1.2 on 2022-10-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="psychologist",
            name="bio",
            field=models.TextField(
                blank=True, null=True, verbose_name="Biografia/Descrição"
            ),
        ),
        migrations.AddField(
            model_name="psychologist",
            name="instagram_link",
            field=models.URLField(
                blank=True, null=True, verbose_name="Link Instagram Profissional"
            ),
        ),
        migrations.AddField(
            model_name="psychologist",
            name="linkedin_link",
            field=models.URLField(
                blank=True, null=True, verbose_name="Link LinkedIn Profissional"
            ),
        ),
        migrations.AddField(
            model_name="psychologist",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Imagem de Perfil"
            ),
        ),
        migrations.AddField(
            model_name="psychologist",
            name="twitter_link",
            field=models.URLField(
                blank=True, null=True, verbose_name="Link Twitter Profissional"
            ),
        ),
        migrations.AddField(
            model_name="psychologist",
            name="whatsapp_number",
            field=models.URLField(
                blank=True, null=True, verbose_name="WhatsApp Profissional"
            ),
        ),
        migrations.AlterField(
            model_name="psychologist",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Telefone"
            ),
        ),
    ]
