# Generated by Django 4.1.2 on 2022-10-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_psychologist_short_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="psychologist",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media",
                verbose_name="Imagem de Perfil",
            ),
        ),
        migrations.AlterField(
            model_name="psychologist",
            name="whatsapp_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="WhatsApp Profissional",
            ),
        ),
    ]
