# Generated by Django 4.1.2 on 2022-10-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_psychologist_photo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="psychologist",
            name="schedule_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
