# Generated by Django 4.1.2 on 2022-10-24 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_psychologist_schedule_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceModalitiy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now=True, verbose_name="Data de criação"),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, verbose_name="Data de atualização"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Nome da modalidade"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descrição da modalidade"
                    ),
                ),
                (
                    "psychologist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.psychologist",
                        verbose_name="Profissional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modalidade de atendimento",
                "verbose_name_plural": "Modalidades de atendimento",
            },
        ),
    ]
