# Generated by Django 4.1.2 on 2022-10-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_servicemodalitiy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="psychologist",
            name="instagram_link",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Link Instagram Profissional",
            ),
        ),
        migrations.AlterField(
            model_name="psychologist",
            name="linkedin_link",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Link LinkedIn Profissional",
            ),
        ),
        migrations.AlterField(
            model_name="psychologist",
            name="twitter_link",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Link Twitter Profissional",
            ),
        ),
    ]
