# Generated by Django 4.1.2 on 2022-10-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_psychologist_instagram_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="psychologist",
            name="cpf",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="CPF"
            ),
        ),
    ]
