# Generated by Django 4.1.2 on 2022-12-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_psychologist_cpf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="psychologist",
            name="created_at",
            field=models.DateField(auto_now_add=True, verbose_name="Data de criação"),
        ),
        migrations.AlterField(
            model_name="servicemodalitiy",
            name="created_at",
            field=models.DateField(auto_now_add=True, verbose_name="Data de criação"),
        ),
    ]
