# Generated by Django 4.1.2 on 2022-10-10 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("financial_management", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now=True, verbose_name="Data de criação"),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, verbose_name="Data de atualização"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "patient_name",
                    models.CharField(max_length=100, verbose_name="Nome Completo"),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Nascimento"
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="CPF"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=15, verbose_name="Telefone"),
                ),
                (
                    "patient_address",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Endereço"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=100, null=True, verbose_name="E-mail"
                    ),
                ),
                (
                    "occupation",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Profissão"
                    ),
                ),
                (
                    "responsable",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Responsavel",
                    ),
                ),
                (
                    "fone_resp",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Telefone responsavel",
                    ),
                ),
                (
                    "session_week_day",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Dia das sessões",
                    ),
                ),
                (
                    "session_hour",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Hora das sessões",
                    ),
                ),
                (
                    "plain",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="financial_management.paymentplain",
                        verbose_name="Plano",
                    ),
                ),
                (
                    "psychologist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.psychologist",
                        verbose_name="Profissional responsável",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paciente",
                "verbose_name_plural": "Pacientes",
            },
        ),
        migrations.CreateModel(
            name="TherapySession",
            fields=[
                (
                    "created_at",
                    models.DateField(auto_now=True, verbose_name="Data de criação"),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, verbose_name="Data de atualização"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("session_id", models.AutoField(primary_key=True, serialize=False)),
                ("date_session", models.DateField(verbose_name="Data da seção")),
                ("hour_session", models.TimeField(verbose_name="Horário da sessão")),
                (
                    "fault",
                    models.BooleanField(default=False, verbose_name="Paciente faltou?"),
                ),
                (
                    "justify_fault",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Justificativa da falta",
                    ),
                ),
                ("evolution", models.TextField(verbose_name="Evolução do caso")),
                (
                    "forwarding",
                    models.TextField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Encaminhamento",
                    ),
                ),
                (
                    "payment",
                    models.BooleanField(default=False, verbose_name="Pagamento"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient_management.patient",
                        verbose_name="Paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sessão",
                "verbose_name_plural": "Sessões",
            },
        ),
        migrations.CreateModel(
            name="Prontuary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now=True, verbose_name="Data de criação"),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, verbose_name="Data de atualização"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("open_date", models.DateField(verbose_name="Data de abertura")),
                (
                    "close_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de fechamento"
                    ),
                ),
                (
                    "demand_description",
                    models.TextField(verbose_name="Avaliação da demanda"),
                ),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient_management.patient",
                        verbose_name="Paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prontuário",
                "verbose_name_plural": "Prontuários",
            },
        ),
    ]
