# Generated by Django 4.1.2 on 2022-10-17 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("patient_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="therapysession",
            name="prontuary",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="patient_management.prontuary",
                verbose_name="Paciente",
            ),
        ),
        migrations.AlterField(
            model_name="prontuary",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="patient_management.patient",
                verbose_name="Paciente",
            ),
        ),
        migrations.AlterField(
            model_name="therapysession",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="patient_management.patient",
                verbose_name="Paciente",
            ),
        ),
    ]
