# Generated by Django 4.1.2 on 2022-10-17 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "patient_management",
            "0002_therapysession_prontuary_alter_prontuary_patient_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="fone_resp",
            new_name="phone_resp",
        ),
        migrations.AddField(
            model_name="patient",
            name="father",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nome do pai"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="mother",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nome da mãe"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="phone_father",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Telefone do pai"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="phone_mother",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Telefone da mãe"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="school",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Escola"
            ),
        ),
        migrations.AlterField(
            model_name="therapysession",
            name="prontuary",
            field=models.ForeignKey(
                default=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="patient_management.prontuary",
                verbose_name="Prontuário",
            ),
        ),
    ]
