# Generated by Django 4.1.2 on 2022-10-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "patient_management",
            "0003_rename_fone_resp_patient_phone_resp_patient_father_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="prontuary",
            name="prontuary_number",
            field=models.CharField(
                default="1", max_length=10, verbose_name="Número do prontuário"
            ),
        ),
    ]
