# Generated by Django 4.1.2 on 2022-10-17 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("patient_management", "0004_prontuary_prontuary_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="therapysession",
            name="prontuary",
            field=models.ForeignKey(
                blank=True,
                default=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="patient_management.prontuary",
                verbose_name="Prontuário",
            ),
        ),
    ]
