# Generated by Django 4.1.2 on 2022-12-22 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_psychologist_created_at_and_more"),
        (
            "patient_management",
            "0007_alter_patient_created_at_alter_prontuary_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="prontuary",
            name="type_of_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.servicemodalitiy",
                verbose_name="Tipo de atendimento",
            ),
        ),
    ]
