# Generated by Django 4.1.2 on 2023-01-04 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patient_management", "0009_alter_patient_cpf"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="therapysession",
            name="patient",
        ),
    ]
