from django.urls import path

from .views import *

# home views
urlpatterns = [
    path(
        "",
        home,
        name="home",
    ),
    path(
        "professional_description/<int:id>/",
        professional_description,
        name="professional_description",
    ),
    path(
        "login/",
        login_view,
        name="login",
    ),
    path(
        "login/create/",
        login_create,
        name="login_create",
    ),
    path(
        "logout/",
        logout_view,
        name="logout",
    ),
    path(
        "my_profile/",
        my_profile_update,
        name="my_profile",
    ),
]

# payment plains urls
urlpatterns += [
    path(
        "payment_plains/",
        payment_plains_list,
        name="payment_plains",
    ),
    path(
        "payment_plains/create/",
        create_payment_plain,
        name="create_payment_plain",
    ),
    path(
        "payment_plains/save/",
        payment_plain_save,
        name="payment_plain_save",
    ),
    path(
        "payment_plain/<int:id>/update/",
        payment_plain_update,
        name="payment_plain_update",
    ),
    path(
        "payment_plain/<int:id>/archive/",
        payment_plain_archive,
        name="payment_plain_archive",
    ),
    path(
        "payment_plain/<int:id>/archive_confirm/",
        payment_plain_archive_confirm,
        name="payment_plain_archive_confirm",
    ),
    path(
        "payment_plains/archived/",
        payment_plains_archived,
        name="payment_plains_arquived",
    ),
    path(
        "payment_plain/<int:id>/unarchive/",
        payment_plain_unarchive,
        name="payment_plain_unarchive",
    ),
    path(
        "payment_plain/<int:id>/delete/",
        payment_plain_delete,
        name="payment_plain_delete",
    ),
    path(
        "payment_plain/<int:id>/delete_confirm/",
        payment_plain_delete_confirm,
        name="payment_plain_delete_confirm",
    ),
]

# patients urls
urlpatterns += [
    path(
        "patients/",
        patients_list,
        name="patients_list",
    ),
    path(
        "patients/create/",
        create_patient,
        name="create_patient",
    ),
    path(
        "patients/save/",
        patient_save,
        name="patient_save",
    ),
    path(
        "patients/<int:id>/update/",
        patient_update,
        name="patient_update",
    ),
    path(
        "patient/<int:id>/archive/",
        patient_archive,
        name="patient_archive",
    ),
    path(
        "patient/<int:id>/archive_confirm/",
        patient_archive_confirm,
        name="patient_archive_confirm",
    ),
    path(
        "patients/archived/",
        patients_archived,
        name="patients_arquived",
    ),
    path(
        "patient/<int:id>/unarchive/",
        patient_unarchive,
        name="patient_unarchive",
    ),
    path(
        "patient/<int:id>/delete/",
        patient_delete,
        name="patient_delete",
    ),
    path(
        "patient/<int:id>/delete_confirm/",
        patient_delete_confirm,
        name="patient_delete_confirm",
    ),
]

# prontuaries urls
urlpatterns += [
    path(
        "prontuaries/",
        prontuaries_list,
        name="prontuaries_list",
    ),
    path(
        "prontuaries/create/",
        create_prontuary,
        name="create_prontuary",
    ),
    path(
        "prontuaries/save/",
        prontuary_save,
        name="prontuary_save",
    ),
    path(
        "prontuaries/<int:id>/update/",
        prontuary_update,
        name="prontuary_update",
    ),
    path(
        "prontuary/<int:id>/",
        prontuary_details,
        name="prontuary_details",
    ),
    path(
        "prontuary/<int:id>/archive/",
        prontuary_archive,
        name="prontuary_archive",
    ),
    path(
        "prontuary/<int:id>/archive_confirm/",
        prontuary_archive_confirm,
        name="prontuary_archive_confirm",
    ),
    path(
        "prontuaries/archived/",
        prontuaries_archived,
        name="prontuaries_arquived",
    ),
    path(
        "prontuary/<int:id>/unarchive/",
        prontuary_unarchive,
        name="prontuary_unarchive",
    ),
    path(
        "prontuary/<int:id>/delete/",
        prontuary_delete,
        name="prontuary_delete",
    ),
    path(
        "prontuary/<int:id>/delete_confirm/",
        prontuary_delete_confirm,
        name="prontuary_delete_confirm",
    ),
]

# therapy sessions urls
urlpatterns += [
    path(
        "prontuaries/<int:id>/create_session/",
        create_therapy_session,
        name="create_session",
    ),
    path(
        "prontuaries/<int:id>/create_session/save/",
        therapy_session_save,
        name="therapy_session_save",
    ),
    path(
        "therapy_session/<int:id>/update/",
        therapy_session_update,
        name="therapy_session_update",
    ),
    path(
        "therapy_session/<int:id>/update_payment/",
        therapy_session_update_payment,
        name="therapy_session_update_payment",
    ),
    path(
        "therapy_session/<int:id>/update_fault/",
        therapy_session_update_fault,
        name="therapy_session_update_fault",
    ),
    path(
        "therapy_session/<int:id>/delete/",
        therapy_session_delete,
        name="therapy_session_delete",
    ),
    path(
        "therapy_session/<int:id>/delete_confirm/",
        therapy_session_delete_confirm,
        name="therapy_session_delete_confirm",
    ),
]

# report urls
urlpatterns += [
    path(
        "pending_session_payments_report/",
        pending_session_payments_report,
        name="pending_session_payments_report",
    ),
    path(
        "paid_session_payments_report/",
        paid_session_payments_report,
        name="paid_session_payments_report",
    ),
    path(
        "therapy_session_payments_report/",
        therapy_session_payments_report,
        name="therapy_session_payments_report",
    ),
    path(
        "payment_control_report/",
        payment_control_report,
        name="payment_control_report",
    ),
    path(
        "payment_receipt/<int:id>/",
        payment_receipt,
        name="payment_receipt",
    ),
]

# service modalities
urlpatterns += [
    path(
        "service_modalities/",
        service_modalities_list,
        name="service_modalities",
    ),
    path(
        "service_modalities/create/",
        create_service_modality,
        name="create_service_modality",
    ),
    path(
        "service_modalities/save/",
        service_modality_save,
        name="service_modality_save",
    ),
    path(
        "service_modalities/<int:id>/update/",
        service_modality_update,
        name="service_modality_update",
    ),
    path(
        "service_modalities/<int:id>/archive_confirm/",
        service_modality_archive_confirm,
        name="service_modality_archive_confirm",
    ),
    path(
        "service_modalities/<int:id>/archive/",
        service_modality_archive,
        name="service_modality_archive",
    ),
    path(
        "service_modalities/archived/",
        service_modalities_archived,
        name="service_modalities_archived",
    ),
    path(
        "service_modalities/<int:id>/unarchive/",
        service_modality_unarchive,
        name="service_modality_unarchive",
    ),
    path(
        "service_modalities/<int:id>/delete/",
        service_modality_delete,
        name="service_modality_delete",
    ),
    path(
        "service_modalities/<int:id>/delete_confirm/",
        service_modality_delete_confirm,
        name="service_modality_delete_confirm",
    ),
]

# payment_control
urlpatterns += [
    path(
        "payment_control/",
        payment_control_list,
        name="payment_control",
    ),
    path(
        "payment_control/create/",
        create_payment_control,
        name="create_payment_control",
    ),
    path(
        "payment_control/save/",
        payment_control_save,
        name="payment_control_save",
    ),
    path(
        "payment_control/<int:id>/update/",
        payment_control_update,
        name="payment_control_update",
    ),
    path(
        "payment_control/<int:id>/delete/",
        payment_control_delete,
        name="payment_control_delete",
    ),
    path(
        "payment_control/<int:id>/delete_confirm/",
        payment_control_delete_confirm,
        name="payment_control_delete_confirm",
    ),
]
