from django.urls import path

from .views import *

# home views
urlpatterns = [
    path(
        "",
        home,
        name="home",
    ),
    path(
        "professional_description/<int:id>/",
        professional_description,
        name="professional_description",
    ),
    path(
        "login/",
        login_view,
        name="login",
    ),
    path(
        "login/create/",
        login_create,
        name="login_create",
    ),
    path(
        "logout/",
        logout_view,
        name="logout",
    ),
    path(
        "my_profile/",
        my_profile_update,
        name="my_profile",
    ),
]

# payment plain urls
urlpatterns += [
    path(
        "payment_plain/",
        payment_plains_list,
        name="payment_plain",
    ),
    path(
        "payment_plain/create/",
        create_payment_plain,
        name="create_payment_plain",
    ),
    path(
        "payment_plain/save/",
        payment_plain_save,
        name="payment_plain_save",
    ),
    path(
        "payment_plain/<int:id>/update/",
        payment_plain_update,
        name="payment_plain_update",
    ),
    path(
        "payment_plain/<int:id>/archive/",
        payment_plain_archive,
        name="payment_plain_archive",
    ),
    path(
        "payment_plain/<int:id>/archive_confirm/",
        payment_plain_archive_confirm,
        name="payment_plain_archive_confirm",
    ),
    path(
        "payment_plain/archived/",
        payment_plains_archived,
        name="payment_plain_archived",
    ),
    path(
        "payment_plain/<int:id>/unarchive/",
        payment_plain_unarchive,
        name="payment_plain_unarchive",
    ),
    path(
        "payment_plain/<int:id>/delete/",
        payment_plain_delete,
        name="payment_plain_delete",
    ),
    path(
        "payment_plain/<int:id>/delete_confirm/",
        payment_plain_delete_confirm,
        name="payment_plain_delete_confirm",
    ),
]

# patient urls
urlpatterns += [
    path(
        "patient/",
        patients_list,
        name="patient",
    ),
    path(
        "patient/create/",
        create_patient,
        name="create_patient",
    ),
    path(
        "patient/save/",
        patient_save,
        name="patient_save",
    ),
    path(
        "patient/<int:id>/update/",
        patient_update,
        name="patient_update",
    ),
    path(
        "patient/<int:id>/archive/",
        patient_archive,
        name="patient_archive",
    ),
    path(
        "patient/<int:id>/archive_confirm/",
        patient_archive_confirm,
        name="patient_archive_confirm",
    ),
    path(
        "patient/archived/",
        patients_archived,
        name="patient_archived",
    ),
    path(
        "patient/<int:id>/unarchive/",
        patient_unarchive,
        name="patient_unarchive",
    ),
    path(
        "patient/<int:id>/delete/",
        patient_delete,
        name="patient_delete",
    ),
    path(
        "patient/<int:id>/delete_confirm/",
        patient_delete_confirm,
        name="patient_delete_confirm",
    ),
]

# prontuary urls
urlpatterns += [
    path(
        "prontuary/",
        prontuaries_list,
        name="prontuary",
    ),
    path(
        "prontuary/create/",
        create_prontuary,
        name="create_prontuary",
    ),
    path(
        "prontuary/save/",
        prontuary_save,
        name="prontuary_save",
    ),
    path(
        "prontuary/<int:id>/update/",
        prontuary_update,
        name="prontuary_update",
    ),
    path(
        "prontuary/<int:id>/",
        prontuary_details,
        name="prontuary_details",
    ),
    path(
        "prontuary/<int:id>/archive/",
        prontuary_archive,
        name="prontuary_archive",
    ),
    path(
        "prontuary/<int:id>/archive_confirm/",
        prontuary_archive_confirm,
        name="prontuary_archive_confirm",
    ),
    path(
        "prontuary/archived/",
        prontuaries_archived,
        name="prontuary_archived",
    ),
    path(
        "prontuary/<int:id>/unarchive/",
        prontuary_unarchive,
        name="prontuary_unarchive",
    ),
    path(
        "prontuary/<int:id>/delete/",
        prontuary_delete,
        name="prontuary_delete",
    ),
    path(
        "prontuary/<int:id>/delete_confirm/",
        prontuary_delete_confirm,
        name="prontuary_delete_confirm",
    ),
]

# therapy sessions urls
urlpatterns += [
    path(
        "prontuary/<int:id>/create_session/",
        create_therapy_session,
        name="create_session",
    ),
    path(
        "prontuary/<int:id>/create_session/save/",
        therapy_session_save,
        name="therapy_session_save",
    ),
    path(
        "therapy_session/<int:id>/update/",
        therapy_session_update,
        name="therapy_session_update",
    ),
    path(
        "therapy_session/<int:id>/update_payment/",
        therapy_session_update_payment,
        name="therapy_session_update_payment",
    ),
    path(
        "therapy_session/<int:id>/update_fault/",
        therapy_session_update_fault,
        name="therapy_session_update_fault",
    ),
    path(
        "therapy_session/<int:id>/delete/",
        therapy_session_delete,
        name="therapy_session_delete",
    ),
    path(
        "therapy_session/<int:id>/delete_confirm/",
        therapy_session_delete_confirm,
        name="therapy_session_delete_confirm",
    ),
]

# report urls
urlpatterns += [
    path(
        "therapy_session_payment_report/",
        therapy_session_payments_report,
        name="therapy_session_payment_report",
    ),
    path(
        "payment_control_report/",
        payment_control_report,
        name="payment_control_report",
    ),
    path(
        "payment_receipt/<int:id>/",
        payment_receipt,
        name="payment_receipt",
    ),
    path(
        "expense_control_report/",
        expense_control_report,
        name="expense_control_report",
    ),
]

# service modalities
urlpatterns += [
    path(
        "service_modality/",
        service_modalities_list,
        name="service_modality",
    ),
    path(
        "service_modality/create/",
        create_service_modality,
        name="create_service_modality",
    ),
    path(
        "service_modality/save/",
        service_modality_save,
        name="service_modality_save",
    ),
    path(
        "service_modality/<int:id>/update/",
        service_modality_update,
        name="service_modality_update",
    ),
    path(
        "service_modality/<int:id>/archive_confirm/",
        service_modality_archive_confirm,
        name="service_modality_archive_confirm",
    ),
    path(
        "service_modality/<int:id>/archive/",
        service_modality_archive,
        name="service_modality_archive",
    ),
    path(
        "service_modality/archived/",
        service_modalities_archived,
        name="service_modality_archived",
    ),
    path(
        "service_modality/<int:id>/unarchive/",
        service_modality_unarchive,
        name="service_modality_unarchive",
    ),
    path(
        "service_modality/<int:id>/delete/",
        service_modality_delete,
        name="service_modality_delete",
    ),
    path(
        "service_modality/<int:id>/delete_confirm/",
        service_modality_delete_confirm,
        name="service_modality_delete_confirm",
    ),
]

# payment_control
urlpatterns += [
    path(
        "payment_control/",
        payment_control_list,
        name="payment_control",
    ),
    path(
        "payment_control/create/",
        create_payment_control,
        name="create_payment_control",
    ),
    path(
        "payment_control/save/",
        payment_control_save,
        name="payment_control_save",
    ),
    path(
        "payment_control/<int:id>/update/",
        payment_control_update,
        name="payment_control_update",
    ),
    path(
        "payment_control/<int:id>/delete/",
        payment_control_delete,
        name="payment_control_delete",
    ),
    path(
        "payment_control/<int:id>/delete_confirm/",
        payment_control_delete_confirm,
        name="payment_control_delete_confirm",
    ),
]

# expense categories
urlpatterns += [
    path(
        "expense_category/",
        expense_categories_list,
        name="expense_category",
    ),
    path(
        "expense_category/create/",
        create_expense_category,
        name="create_expense_category",
    ),
    path(
        "expense_category/save/",
        expense_category_save,
        name="expense_category_save",
    ),
    path(
        "expense_category/<int:id>/update/",
        expense_category_update,
        name="expense_category_update",
    ),
    path(
        "expense_category/<int:id>/archive_confirm/",
        expense_category_archive_confirm,
        name="expense_category_archive_confirm",
    ),
    path(
        "expense_category/<int:id>/archive/",
        expense_category_archive,
        name="expense_category_archive",
    ),
    path(
        "expense_category/archived/",
        expense_categories_archived,
        name="expense_category_archived",
    ),
    path(
        "expense_category/<int:id>/unarchive/",
        expense_category_unarchive,
        name="expense_category_unarchive",
    ),
    path(
        "expense_category/<int:id>/delete/",
        expense_category_delete,
        name="expense_category_delete",
    ),
    path(
        "expense_category/<int:id>/delete_confirm/",
        expense_category_delete_confirm,
        name="expense_category_delete_confirm",
    ),
]

# expense control
urlpatterns += [
    path(
        "expense_control/",
        expense_control_list,
        name="expense_control",
    ),
    path(
        "expense_control/create/",
        create_expense_control,
        name="create_expense_control",
    ),
    path(
        "expense_control/save/",
        expense_control_save,
        name="expense_control_save",
    ),
    path(
        "expense_control/<int:id>/update/",
        expense_control_update,
        name="expense_control_update",
    ),
    path(
        "expense_control/<int:id>/delete/",
        expense_control_delete,
        name="expense_control_delete",
    ),
    path(
        "expense_control/<int:id>/delete_confirm/",
        expense_control_delete_confirm,
        name="expense_control_delete_confirm",
    ),
]
