# Generated by Django 4.1.2 on 2022-10-07 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now=True, verbose_name="Data de criação"),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, verbose_name="Data de atualização"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "value_pay",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Valor pago"
                    ),
                ),
                ("data_pay", models.DateField(verbose_name="Data de pagamento")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Descrição do pagamento",
                    ),
                ),
                (
                    "way_pay",
                    models.CharField(
                        choices=[
                            ("Pix", "Pix"),
                            ("Dinheiro", "Money"),
                            ("Transferência", "Trasnferency"),
                            ("Cheque", "Check"),
                        ],
                        max_length=50,
                        verbose_name="Forma de pagamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pagamento",
                "verbose_name_plural": "Pagamentos",
            },
        ),
        migrations.CreateModel(
            name="PaymentPlain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now=True, verbose_name="Data de criação"),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, verbose_name="Data de atualização"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "name_plain",
                    models.CharField(max_length=30, verbose_name="Descrição"),
                ),
                (
                    "plain_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Valor Plano (R$)"
                    ),
                ),
                (
                    "psycologist",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.psychologist",
                        verbose_name="Profissional responsável",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plano de pagamento",
                "verbose_name_plural": "Planos de pagamento",
            },
        ),
    ]
