# Generated by Django 4.1.2 on 2022-10-10 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("financial_management", "0001_initial"),
        ("patient_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentcontrol",
            name="pacient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="patient_management.patient",
                verbose_name="Paciente",
            ),
        ),
        migrations.AddField(
            model_name="paymentcontrol",
            name="therapy_sessions",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="patient_management.therapysession",
                verbose_name="Sessões",
            ),
        ),
    ]
