# Generated by Django 4.1.2 on 2022-10-17 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial_management", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentcontrol",
            name="description",
            field=models.TextField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Descrição do pagamento",
            ),
        ),
    ]
