# Generated by Django 4.1.2 on 2022-11-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient_management", "0005_alter_therapysession_prontuary"),
        (
            "financial_management",
            "0004_expensecategory_alter_paymentcontrol_way_pay_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentcontrol",
            name="checking_copy",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media",
                verbose_name="Comprovante de pagamento",
            ),
        ),
        migrations.AddField(
            model_name="paymentcontrol",
            name="therapy_session",
            field=models.ManyToManyField(
                blank=True,
                to="patient_management.therapysession",
                verbose_name="Sessões",
            ),
        ),
    ]
