# Generated by Django 4.1.2 on 2022-12-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial_management", "0005_paymentcontrol_checking_copy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expensecategory",
            name="created_at",
            field=models.DateField(auto_now_add=True, verbose_name="Data de criação"),
        ),
        migrations.AlterField(
            model_name="expensecontrol",
            name="created_at",
            field=models.DateField(auto_now_add=True, verbose_name="Data de criação"),
        ),
        migrations.AlterField(
            model_name="paymentcontrol",
            name="created_at",
            field=models.DateField(auto_now_add=True, verbose_name="Data de criação"),
        ),
        migrations.AlterField(
            model_name="paymentplain",
            name="created_at",
            field=models.DateField(auto_now_add=True, verbose_name="Data de criação"),
        ),
    ]
