# Generated by Django 4.1.2 on 2022-12-21 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "patient_management",
            "0007_alter_patient_created_at_alter_prontuary_created_at_and_more",
        ),
        ("financial_management", "0006_alter_expensecategory_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paymentcontrol",
            old_name="data_pay",
            new_name="date_of_pay",
        ),
        migrations.RenameField(
            model_name="paymentcontrol",
            old_name="way_pay",
            new_name="payment_method",
        ),
        migrations.RenameField(
            model_name="paymentcontrol",
            old_name="value_pay",
            new_name="value_paid",
        ),
        migrations.RemoveField(
            model_name="paymentcontrol",
            name="patient",
        ),
        migrations.AddField(
            model_name="paymentcontrol",
            name="prontuary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="patient_management.prontuary",
                verbose_name="Prontuário",
            ),
        ),
        migrations.AlterField(
            model_name="paymentcontrol",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Descrição do pagamento"
            ),
        ),
    ]
