# Generated by Django 4.1.2 on 2022-12-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "financial_management",
            "0007_rename_data_pay_paymentcontrol_date_of_pay_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentcontrol",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Descrição do pagamento"
            ),
        ),
    ]
